import { Button, ListView } from "std-widgets.slint";
import { ColorPalette } from "color_palette.slint";
import { Translations } from "translations.slint";

export component ContextMenu inherits PopupWindow {
    in property <bool> show_directory_options: true;
    in property <int> selected_index: -1;

    callback open_path(int);
    callback copy_path(int);
    callback select_tree(int);
    callback select_other(int);

    width: 300px; // Slightly wider for translations
    height: show_directory_options ? 140px : 70px;

    Rectangle {
        background: ColorPalette.popup_background;
        border-radius: 4px;
        border-width: 1px;
        border-color: ColorPalette.text_color;

        VerticalLayout {
            padding: 5px;
            spacing: 5px;

            Button {
                text: Translations.context_menu_open_path;
                clicked => { root.open_path(root.selected_index); root.close(); }
            }
            Button {
                text: Translations.context_menu_copy_path;
                clicked => { root.copy_path(root.selected_index); root.close(); }
            }
            if show_directory_options : Button {
                text: Translations.context_menu_select_tree;
                clicked => { root.select_tree(root.selected_index); root.close(); }
            }
            if show_directory_options : Button {
                text: Translations.context_menu_select_other;
                clicked => { root.select_other(root.selected_index); root.close(); }
            }
        }
    }
}
