import { Button, ListView } from "std-widgets.slint";
import { ColorPalette } from "color_palette.slint";

export component ContextMenu inherits PopupWindow {
    in property <length> menu_x;
    in property <length> menu_y;
    in property <bool> show_directory_options: true;

    callback open_path();
    callback copy_path();
    callback select_tree();
    callback select_other();

    x: menu_x;
    y: menu_y;
    width: 250px;
    height: show_directory_options ? 140px : 70px; // Adjust based on items

    Rectangle {
        background: ColorPalette.popup_background;
        border-radius: 4px;
        border-width: 1px;
        border-color: ColorPalette.text_color;

        VerticalLayout {
            padding: 5px;
            spacing: 5px;

            Button {
                text: "Open File Path";
                clicked => { root.open_path(); root.close(); }
            }
            Button {
                text: "Copy File Path";
                clicked => { root.copy_path(); root.close(); }
            }
            if show_directory_options : Button {
                text: "Select duplicates in tree...";
                clicked => { root.select_tree(); root.close(); }
            }
            if show_directory_options : Button {
                text: "Select duplicates in other...";
                clicked => { root.select_other(); root.close(); }
            }
        }
    }
}
