import { LineEdit, CheckBox, Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { PopupBase } from "popup_base.slint";
import { Translations } from "translations.slint";
import { Callabler } from "callabler.slint";

export component PopupCustomSelect inherits Rectangle {
    out property <length> popup_width: 400px;
    out property <length> popup_height: 300px;
    callback show_popup();
    callback close_popup();

    private property <string> text_data;
    private property <bool> use_regex: false;
    private property <bool> case_sensitive: false;
    private property <bool> not_in: false;

    popup_window := PopupBase {
        width: popup_width;
        height: popup_height;
        title_text: "自定义选择"; // TODO: Translation
        // Hide default OK button as we have custom action buttons
        enabled_ok_button: false;
        
        VerticalBox {
            LineEdit {
                placeholder-text: "输入文本或正则表达式...";
                text <=> text_data;
            }
            
            HorizontalBox {
                CheckBox {
                    text: "正则";
                    checked <=> use_regex;
                }
                CheckBox {
                    text: "区分大小写";
                    checked <=> case_sensitive;
                }
                CheckBox {
                    text: "反选";
                    checked <=> not_in;
                }
            }

            HorizontalBox {
                Button {
                    text: "选择";
                    enabled: text_data != "";
                    clicked => {
                        Callabler.custom_selection(text_data, use_regex, case_sensitive, not_in, true);
                        popup_window.close();
                    }
                }
                Button {
                    text: "取消选择";
                    enabled: text_data != "";
                    clicked => {
                        Callabler.custom_selection(text_data, use_regex, case_sensitive, not_in, false);
                        popup_window.close();
                    }
                }
            }
        }
    }

    show_popup() => {
        text_data = "";
        popup_window.show();
    }
    close_popup() => {
        popup_window.close();
    }
}
